name: CI Firebase Functions Lint
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14", "16"]
    name: Node ${{ matrix.node }} CI Firebae Functions Lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm install
        working-directory: ./functions
      - run: npm run lint --if-present
        working-directory: ./functions
