name: dev CD Firebase
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14", "16"]
    name: dev Node ${{ matrix.node }} CD Firebase
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint --if-present
      - run: npm run build:dev --if-present
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm install
        working-directory: ./functions
      - run: npm run lint --if-present
        working-directory: ./functions
      - run: npm run build --if-present
        working-directory: ./functions
      - run: npx firebase deploy  --project=dev-template-angular-firebase --token=${{ secrets.FIREBASE_TOKEN }}
