name: dev CI Angular E2E Test
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14", "16"]
    name: dev Node ${{ matrix.node }} CI Angular E2E Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run e2e:ci:dev
